### PR TITLE
changed the speak function

### PR DESCRIPTION
**Pull request by kshitij98-Cpp**
Makes it less robotic. but still u need to test, whether it gives the answers of the questions

### CODE REVIEW

**Comment by advabatit** [comment]
What do you mean?

**Comment by advabatit** [comment]
I tried it to use gTTS, but it takes too much time to load..

**Comment by kshitij98-Cpp** [comment]
The narrator voice of pyttsx seems so robotic. For best experience the Gtts is best. but yeah it also has cons too, like sometimes it takes some time to speak because it all depends on internet connection.

**Comment by kshitij98-Cpp** [comment]
> 
> 
> What do you mean?

I was saying that i was confused what to ask when the narrator stops speaking and when "You can speak" displays on the prompt/terminal.

**Comment by advabatit** [comment]
Got it. I think that the speak function will still stay the same, but I'll change the first paragraph so that when the virtual assistant reads, it will be more clear when to speak. Thank you :)

**Comment by kshitij98-Cpp** [comment]
> 
> 
> Got it. I think that the speak function will still stay the same, but I'll change the first paragraph so that when the virtual assistant reads, it will be more clear when to speak. Thank you :)

so u gonna stick with pyttsx ?

**Pull request closed without merging**
